services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:9092"

  ingest-service:
    build: ./ingest_service
    container_name: ingest-service
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8000"

  timescaledb:
    image: timescale/timescaledb:2.14.2-pg14
    container_name: timescaledb
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: analytics_pass
    ports:
      - "5433:5432"
    volumes:
      - ./consumer_service/init.sql:/docker-entrypoint-initdb.d/init.sql

  consumer-service:
    build: ./consumer_service
    container_name: consumer-service
    depends_on:
      - kafka
      - timescaledb
    environment:
      KAFKA_BROKER: kafka:9092
      DB_HOST: timescaledb
      DB_NAME: analytics
      DB_USER: analytics_user
      DB_PASS: analytics_pass
  
  event-generator:
    build: ./event_generator
    depends_on:
      - ingest-service
    restart: always

volumes:
  timescale_data:
